[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
solc_version = '0.8.28'
evm_version = 'paris'
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.local]
eth_rpc_url = "http://localhost:8545"

[profile.base_sepolia]
eth_rpc_url = "${BASE_SEPOLIA_RPC_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
local = "http://localhost:8545"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
