name: Build and Tests
on: [push]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Pre-install
        run: |
          rm -rf node_modules
          yarn install

      - name: Lint
        run: |
          yarn lint

      - name: Compile
        run: |
          yarn clean
          yarn compile

      - name: Run Anvil
        run: |
          ./scripts/bin/anvil.sh

      - name: Deploy Contracts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        run: |
          source .env.hardhat.sh
          yarn deploy:local
                    
      - name: Run Unit Tests
        run: |
          yarn test
          
      - name: Run Integration Tests
        run: |
          yarn test:integration
