name: Foundry Deployment tests
on: [push]

permissions:
  contents: write

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Pre-install
        run: |
          rm -rf node_modules
          yarn install

      - name: Compile
        run: |
          yarn clean
          yarn compile  

      - name: Run Anvil
        run: |
          anvil &         
      - name: Deploy Contracts
        env:
          RPC_URL: "http://localhost:8545"
          OWNER_MNEMONIC: "test test test test test test test test test test test junk"
          OWNER_INDEX: 0
          OWNER_ADDRESS: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
          GOVERNOR_MNEMONIC: "test test test test test test test test test test test junk"
          GOVERNOR_INDEX: 1
          GOVERNOR_ADDRESS: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
          NVM_FEE_AMOUNT: 10000
          NVM_FEE_RECEIVER: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
          DEPLOYMENT_ADDRESSES_JSON: "deployment-latest.json"
          ETHERSCAN_API_KEY: "xx"

        run: |
          forge script scripts/deploy/DeployAll.sol --rpc-url $RPC_URL --broadcast --mnemonics "$OWNER_MNEMONIC" --mnemonic-indexes $OWNER_INDEX --sender $OWNER_ADDRESS
          forge script scripts/deploy/ConfigureAll.sol --rpc-url $RPC_URL --broadcast --mnemonics "$GOVERNOR_MNEMONIC" --mnemonic-indexes $GOVERNOR_INDEX --sender $GOVERNOR_ADDRESS
          
