name: Test Contract Upgradeability

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable          

      - name: Install dependencies
        run: yarn install


      - name: Run Anvil
        run: |
          anvil &         
      - name: Deploy Contracts
        env:
          RPC_URL: "http://localhost:8545"
          OWNER_MNEMONIC: "test test test test test test test test test test test junk"
          OWNER_INDEX: 0
          OWNER_ADDRESS: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
          GOVERNOR_MNEMONIC: "test test test test test test test test test test test junk"
          GOVERNOR_INDEX: 1
          GOVERNOR_ADDRESS: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
          NVM_FEE_AMOUNT: 10000
          NVM_FEE_RECEIVER: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
          DEPLOYMENT_ADDRESSES_JSON: "deployment-latest.json"
          ETHERSCAN_API_KEY: "xx"

        run: |
          forge script scripts/deploy/DeployAll.sol --rpc-url $RPC_URL --broadcast --mnemonics "$OWNER_MNEMONIC" --mnemonic-indexes $OWNER_INDEX --sender $OWNER_ADDRESS
          forge script scripts/deploy/ConfigureAll.sol --rpc-url $RPC_URL --broadcast --mnemonics "$GOVERNOR_MNEMONIC" --mnemonic-indexes $GOVERNOR_INDEX --sender $GOVERNOR_ADDRESS
                    
              
      - name: Run upgradeability tests
        run: yarn test:upgrades
